apiVersion: v1
name: busybox
version: 0.1.0
appVersion: 13.0.20200610
description:  A utility chart to verify clusters and processes
home: https://www.busybox.net/
icon: https://www.busybox.net/images/busybox1.png
keywords:
  - busybox 
  - testing 
  - sanity check
  - network
  - connectivity
sources:
- https://github.com/bitnami/bitnami-docker-odoo
maintainers:
- name: Soltani
  email: h.soltani@khallagh.com
engine: gotpl
